# Generated by Django 4.2 on 2023-04-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('language_image', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.AutoField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashspeak.language')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('front_card', models.CharField(max_length=255)),
                ('back_card', models.CharField(max_length=255)),
                ('image_card', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat', models.PositiveSmallIntegerField(choices=[(0, 'Again (< 1 day)'), (1, 'One day later'), (2, 'Four days later'), (3, 'Twenty-one days later')], default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashspeak.deck')),
            ],
        ),
    ]
