# Generated by Django 4.2 on 2023-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashspeak', '0002_topic_alter_deck_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not learned'), (1, 'Learned')], default=0),
        ),
    ]
